// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCREENMAIN_H
#define UI_SCREENMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMain
extern void ui_ScreenMain_screen_init(void);
extern void ui_ScreenMain_screen_destroy(void);
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_Image2;
extern void ui_event_LabelTemp0(lv_event_t * e);
extern lv_obj_t * ui_LabelTemp0;
extern void ui_event_LabelWind(lv_event_t * e);
extern lv_obj_t * ui_LabelWind;
extern lv_obj_t * ui_LabelWindDir;
extern lv_obj_t * ui_LabelLU0;
extern lv_obj_t * ui_LabelTime;
extern void ui_event_ButtonSettings(lv_event_t * e);
extern lv_obj_t * ui_ButtonSettings;
extern lv_obj_t * ui_Label1;
extern void ui_event_LabelTemp1(lv_event_t * e);
extern lv_obj_t * ui_LabelTemp1;
extern void ui_event_LabelHum0(lv_event_t * e);
extern lv_obj_t * ui_LabelHum0;
extern void ui_event_LabelHum2(lv_event_t * e);
extern lv_obj_t * ui_LabelHum2;
extern void ui_event_LabelHum1(lv_event_t * e);
extern lv_obj_t * ui_LabelHum1;
extern void ui_event_LabelPres0(lv_event_t * e);
extern lv_obj_t * ui_LabelPres0;
extern void ui_event_LabelHum3(lv_event_t * e);
extern lv_obj_t * ui_LabelHum3;
extern void ui_event_LabelTemp2(lv_event_t * e);
extern lv_obj_t * ui_LabelTemp2;
extern void ui_event_LabelTemp3(lv_event_t * e);
extern lv_obj_t * ui_LabelTemp3;
extern void ui_event_LabelPres3(lv_event_t * e);
extern lv_obj_t * ui_LabelPres3;
extern void ui_event_LabelPres2(lv_event_t * e);
extern lv_obj_t * ui_LabelPres2;
extern void ui_event_LabelPres1(lv_event_t * e);
extern lv_obj_t * ui_LabelPres1;
extern lv_obj_t * ui_LabelLU1;
extern lv_obj_t * ui_LabelLU2;
extern lv_obj_t * ui_LabelLU3;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label6;
extern void ui_event_LabelWind1(lv_event_t * e);
extern lv_obj_t * ui_LabelWind1;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label21;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

