// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenChart = NULL;
lv_obj_t * ui_Chart1 = NULL;
lv_obj_t * ui_Chart1_Xaxis = NULL;
lv_obj_t * ui_Chart1_Yaxis1 = NULL;
lv_obj_t * ui_Chart1_Yaxis2 = NULL;
lv_obj_t * ui_LabelChart = NULL;
lv_obj_t * ui_ButtonReturn2 = NULL;
lv_obj_t * ui_Label20 = NULL;
// event funtions
void ui_event_ButtonReturn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenMain_screen_init);
    }
}

// build funtions

void ui_ScreenChart_screen_init(void)
{
    ui_ScreenChart = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenChart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chart1 = lv_chart_create(ui_ScreenChart);
    lv_obj_set_width(ui_Chart1, 442);
    lv_obj_set_height(ui_Chart1, 189);
    lv_obj_set_x(ui_Chart1, 9);
    lv_obj_set_y(ui_Chart1, -12);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Chart1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart1, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);

    ui_Chart1_Xaxis = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart1_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart1_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart1_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart1,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Xaxis, 0, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart1_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart1_Xaxis, 0, 0 > 0 ? 0 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart1_Xaxis, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Xaxis, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_Chart1_Xaxis, false);
    ui_Chart1_Yaxis1 = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart1_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart1_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart1_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart1,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart1_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart1_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Yaxis1, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_Chart1_Yaxis1, false);
    ui_Chart1_Yaxis2 = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart1_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart1_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart1_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart1,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart1_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart1_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_Chart1_Yaxis2, false);

    lv_obj_set_style_line_width(ui_Chart1, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_Chart1, 3, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart1, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_LabelChart = lv_label_create(ui_ScreenChart);
    lv_obj_set_width(ui_LabelChart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelChart, 7);
    lv_obj_set_y(ui_LabelChart, 8);
    lv_label_set_text(ui_LabelChart, "==NOT ENOUGH DATA==");
    lv_obj_set_style_text_align(ui_LabelChart, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonReturn2 = lv_button_create(ui_ScreenChart);
    lv_obj_set_width(ui_ButtonReturn2, 100);
    lv_obj_set_height(ui_ButtonReturn2, 25);
    lv_obj_set_x(ui_ButtonReturn2, -179);
    lv_obj_set_y(ui_ButtonReturn2, 117);
    lv_obj_set_align(ui_ButtonReturn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonReturn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReturn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_ScreenChart);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -182);
    lv_obj_set_y(ui_Label20, 118);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "RETURN");

    lv_obj_add_event_cb(ui_ButtonReturn2, ui_event_ButtonReturn2, LV_EVENT_ALL, NULL);

}

void ui_ScreenChart_screen_destroy(void)
{
    if(ui_ScreenChart) lv_obj_del(ui_ScreenChart);

    // NULL screen variables
    ui_ScreenChart = NULL;
    ui_Chart1 = NULL;
    ui_LabelChart = NULL;
    ui_ButtonReturn2 = NULL;
    ui_Label20 = NULL;

}
