// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"
extern void updateBacklightLive(bool autoMode, int offset);
extern void populateWifiList();
extern void applySettingsToUI(void);
lv_obj_t * ui_ScreenSettings = NULL;
lv_obj_t * ui_ButtonReturn = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_LabelIP2 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_ButtonWifi = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Spinbox1 = NULL;
lv_obj_t * ui_Spinbox2 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_LabelConnectedTo = NULL;
lv_obj_t * ui_Spinbox3 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_Spinbox4 = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Label36 = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_Button9 = NULL;
lv_obj_t * ui_Button10 = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_Spinbox5 = NULL;
lv_obj_t * ui_Label40 = NULL;
// event funtions
void ui_event_ButtonReturn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        saveSettings();
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenMain_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        sendSliderValuesToWindTransmitter();
    }
}

void ui_event_ButtonWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenWifi, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenWifi_screen_init);
        populateWifiList();
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox1, -1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_Spinbox1, -1);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_Spinbox2, 1);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox2, 1);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox1, 1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_Spinbox1, 1);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox2, -1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_Spinbox2, -1);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_Spinbox4, 1);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox4, 1);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox4, -1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_Spinbox4, -1);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_Spinbox3, 1);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox3, 1);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox3, -1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_Spinbox3, -1);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox5, -1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_Spinbox5, -1);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_Spinbox5, 1);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox5, 1);
    }
}
// build funtions
// Live brightness preview callbacks
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_VALUE_CHANGED) {
        // Update autoBrightness immediately for live preview
        // saveSettings() will persist it when user exits
        updateBacklightLive(
            lv_obj_has_state(ui_Switch1, LV_STATE_CHECKED),
            (int)lv_spinbox_get_value(ui_Spinbox3)
        );
    }
}

void ui_event_Spinbox3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_VALUE_CHANGED) {
        updateBacklightLive(
            lv_obj_has_state(ui_Switch1, LV_STATE_CHECKED),
            (int)lv_spinbox_get_value(ui_Spinbox3)
        );
    }
}
static void ui_ScreenSettings_on_loaded(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_SCREEN_LOADED) {
        applySettingsToUI();
    }
}


void ui_ScreenSettings_screen_init(void)
{
    ui_ScreenSettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonReturn = lv_button_create(ui_ScreenSettings);
    lv_obj_set_width(ui_ButtonReturn, 100);
    lv_obj_set_height(ui_ButtonReturn, 40);
    lv_obj_set_x(ui_ButtonReturn, 174);
    lv_obj_set_y(ui_ButtonReturn, -16);
    lv_obj_set_align(ui_ButtonReturn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonReturn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReturn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 175);
    lv_obj_set_y(ui_Label2, -16);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "SAVE\n& EXIT");
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -187);
    lv_obj_set_y(ui_Label10, -104);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Average Window (s)");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -195);
    lv_obj_set_y(ui_Label11, -62);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Gust Window (s)");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIP2 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_LabelIP2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIP2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIP2, -129);
    lv_obj_set_y(ui_LabelIP2, 44);
    lv_obj_set_align(ui_LabelIP2, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelIP2, "255.255.255.255");
    lv_obj_set_style_text_font(ui_LabelIP2, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -129);
    lv_obj_set_y(ui_Label9, 27);
    lv_obj_set_align(ui_Label9, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label9, "RSSI: -100dB");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonWifi = lv_button_create(ui_ScreenSettings);
    lv_obj_set_width(ui_ButtonWifi, 100);
    lv_obj_set_height(ui_ButtonWifi, 50);
    lv_obj_set_x(ui_ButtonWifi, 174);
    lv_obj_set_y(ui_ButtonWifi, -91);
    lv_obj_set_align(ui_ButtonWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 174);
    lv_obj_set_y(ui_Label8, -93);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "EDIT\nWIFI");
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -179);
    lv_obj_set_y(ui_Label12, -121);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Wind Settings:");
    lv_obj_set_style_text_decor(ui_Label12, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox1 = lv_spinbox_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Spinbox1, 40);
    lv_obj_set_height(ui_Spinbox1, 16);
    lv_obj_set_x(ui_Spinbox1, -398);
    lv_obj_set_y(ui_Spinbox1, 46);
    lv_obj_set_align(ui_Spinbox1, LV_ALIGN_TOP_RIGHT);
    lv_spinbox_set_digit_format(ui_Spinbox1, 4, 0);
    lv_spinbox_set_range(ui_Spinbox1, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_Spinbox1, 1 - 1);
    lv_spinbox_set_value(ui_Spinbox1, 60);
    lv_obj_set_style_pad_left(ui_Spinbox1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Spinbox1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Spinbox1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Spinbox1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Spinbox1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox1, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox2 = lv_spinbox_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Spinbox2, 40);
    lv_obj_set_height(ui_Spinbox2, 16);
    lv_obj_set_x(ui_Spinbox2, -399);
    lv_obj_set_y(ui_Spinbox2, 89);
    lv_obj_set_align(ui_Spinbox2, LV_ALIGN_TOP_RIGHT);
    lv_spinbox_set_digit_format(ui_Spinbox2, 4, 0);
    lv_spinbox_set_range(ui_Spinbox2, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_Spinbox2, 1 - 1);
    lv_spinbox_set_value(ui_Spinbox2, 1);
    lv_obj_set_style_pad_left(ui_Spinbox2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Spinbox2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Spinbox2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Spinbox2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Spinbox2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox2, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_button_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Button5, 31);
    lv_obj_set_height(ui_Button5, 24);
    lv_obj_set_x(ui_Button5, -219);
    lv_obj_set_y(ui_Button5, -82);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_button_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Button1, 31);
    lv_obj_set_height(ui_Button1, 24);
    lv_obj_set_x(ui_Button1, -141);
    lv_obj_set_y(ui_Button1, -39);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_button_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Button2, 31);
    lv_obj_set_height(ui_Button2, 24);
    lv_obj_set_x(ui_Button2, -140);
    lv_obj_set_y(ui_Button2, -81);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_button_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Button3, 31);
    lv_obj_set_height(ui_Button3, 24);
    lv_obj_set_x(ui_Button3, -219);
    lv_obj_set_y(ui_Button3, -41);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -140);
    lv_obj_set_y(ui_Label22, -81);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "+");
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -141);
    lv_obj_set_y(ui_Label24, -39);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "+");
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -219);
    lv_obj_set_y(ui_Label25, -84);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "-");
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -220);
    lv_obj_set_y(ui_Label26, -43);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "-");
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelConnectedTo = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_LabelConnectedTo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelConnectedTo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelConnectedTo, -129);
    lv_obj_set_y(ui_LabelConnectedTo, 9);
    lv_obj_set_align(ui_LabelConnectedTo, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelConnectedTo, "Connected to:");
    lv_obj_set_style_text_font(ui_LabelConnectedTo, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox3 = lv_spinbox_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Spinbox3, 40);
    lv_obj_set_height(ui_Spinbox3, 16);
    lv_obj_set_x(ui_Spinbox3, -278);
    lv_obj_set_y(ui_Spinbox3, 79);
    lv_obj_set_align(ui_Spinbox3, LV_ALIGN_TOP_RIGHT);
    lv_spinbox_set_digit_format(ui_Spinbox3, 3, 0);
    lv_spinbox_set_range(ui_Spinbox3, 0, 255);
    lv_spinbox_set_cursor_pos(ui_Spinbox3, 1 - 1);
    lv_spinbox_set_value(ui_Spinbox3, 128);
    lv_obj_set_style_pad_left(ui_Spinbox3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Spinbox3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Spinbox3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Spinbox3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Spinbox3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox3, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, -56);
    lv_obj_set_y(ui_Switch1, -100);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch1, LV_STATE_CHECKED);       /// States

    ui_Label27 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -62);
    lv_obj_set_y(ui_Label27, -123);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Brightness:");

    ui_Button7 = lv_button_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Button7, 31);
    lv_obj_set_height(ui_Button7, 24);
    lv_obj_set_x(ui_Button7, -141);
    lv_obj_set_y(ui_Button7, 1);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -59);
    lv_obj_set_y(ui_Label28, -71);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "+");
    lv_obj_set_style_text_font(ui_Label28, &ui_font_Font32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -97);
    lv_obj_set_y(ui_Label29, -101);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Auto:");
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_button_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Button8, 31);
    lv_obj_set_height(ui_Button8, 24);
    lv_obj_set_x(ui_Button8, -219);
    lv_obj_set_y(ui_Button8, 2);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_button_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Button4, 31);
    lv_obj_set_height(ui_Button4, 24);
    lv_obj_set_x(ui_Button4, -20);
    lv_obj_set_y(ui_Button4, -48);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button6 = lv_button_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Button6, 31);
    lv_obj_set_height(ui_Button6, 24);
    lv_obj_set_x(ui_Button6, -97);
    lv_obj_set_y(ui_Button6, -48);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label30 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -98);
    lv_obj_set_y(ui_Label30, -50);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "-");
    lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, -19);
    lv_obj_set_y(ui_Label31, -48);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "+");
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -213);
    lv_obj_set_y(ui_Label32, -19);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "Offset (%)");
    lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -141);
    lv_obj_set_y(ui_Label33, 0);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "+");
    lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -221);
    lv_obj_set_y(ui_Label34, 0);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "-");
    lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox4 = lv_spinbox_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Spinbox4, 40);
    lv_obj_set_height(ui_Spinbox4, 16);
    lv_obj_set_x(ui_Spinbox4, -400);
    lv_obj_set_y(ui_Spinbox4, 130);
    lv_obj_set_align(ui_Spinbox4, LV_ALIGN_TOP_RIGHT);
    lv_spinbox_set_digit_format(ui_Spinbox4, 3, 2);
    lv_spinbox_set_range(ui_Spinbox4, -999, 999);
    lv_spinbox_set_cursor_pos(ui_Spinbox4, 1 - 1);
    lv_obj_set_style_pad_left(ui_Spinbox4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Spinbox4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Spinbox4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Spinbox4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Spinbox4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox4, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, 31);
    lv_obj_set_y(ui_Label35, -50);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "Enable\nCloud:");
    lv_obj_set_style_text_align(ui_Label35, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 88);
    lv_obj_set_y(ui_Switch2, -51);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch2, LV_STATE_CHECKED);       /// States

    ui_Label36 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, -97);
    lv_obj_set_y(ui_Label36, -19);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "Gamma:");
    lv_obj_set_style_text_font(ui_Label36, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, -60);
    lv_obj_set_y(ui_Label37, -16);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "*");
    lv_obj_set_style_text_font(ui_Label37, &ui_font_Font32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_button_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Button9, 31);
    lv_obj_set_height(ui_Button9, 24);
    lv_obj_set_x(ui_Button9, -98);
    lv_obj_set_y(ui_Button9, 1);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button10 = lv_button_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Button10, 31);
    lv_obj_set_height(ui_Button10, 24);
    lv_obj_set_x(ui_Button10, -20);
    lv_obj_set_y(ui_Button10, -1);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label38 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, -98);
    lv_obj_set_y(ui_Label38, -1);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "-");
    lv_obj_set_style_text_font(ui_Label38, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -20);
    lv_obj_set_y(ui_Label39, -1);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "+");
    lv_obj_set_style_text_font(ui_Label39, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox5 = lv_spinbox_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Spinbox5, 40);
    lv_obj_set_height(ui_Spinbox5, 16);
    lv_obj_set_x(ui_Spinbox5, -280);
    lv_obj_set_y(ui_Spinbox5, 128);
    lv_obj_set_align(ui_Spinbox5, LV_ALIGN_TOP_RIGHT);
    lv_spinbox_set_digit_format(ui_Spinbox5, 2, 1);
    lv_spinbox_set_range(ui_Spinbox5, 0, 99);
    lv_spinbox_set_cursor_pos(ui_Spinbox5, 1 - 1);
    lv_spinbox_set_value(ui_Spinbox5, 10);
    lv_obj_set_style_pad_left(ui_Spinbox5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Spinbox5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Spinbox5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Spinbox5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Spinbox5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox5, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, -99);
    lv_obj_set_y(ui_Label40, -71);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "Offset:");
    lv_obj_set_style_text_font(ui_Label40, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonReturn, ui_event_ButtonReturn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonWifi, ui_event_ButtonWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenSettings, ui_ScreenSettings_on_loaded, LV_EVENT_SCREEN_LOADED, NULL);
}

void ui_ScreenSettings_screen_destroy(void)
{
    if(ui_ScreenSettings) lv_obj_del(ui_ScreenSettings);

    // NULL screen variables
    ui_ScreenSettings = NULL;
    ui_ButtonReturn = NULL;
    ui_Label2 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_LabelIP2 = NULL;
    ui_Label9 = NULL;
    ui_ButtonWifi = NULL;
    ui_Label8 = NULL;
    ui_Label12 = NULL;
    ui_Spinbox1 = NULL;
    ui_Spinbox2 = NULL;
    ui_Button5 = NULL;
    ui_Button1 = NULL;
    ui_Button2 = NULL;
    ui_Button3 = NULL;
    ui_Label22 = NULL;
    ui_Label24 = NULL;
    ui_Label25 = NULL;
    ui_Label26 = NULL;
    ui_LabelConnectedTo = NULL;
    ui_Spinbox3 = NULL;
    ui_Switch1 = NULL;
    ui_Label27 = NULL;
    ui_Button7 = NULL;
    ui_Label28 = NULL;
    ui_Label29 = NULL;
    ui_Button8 = NULL;
    ui_Button4 = NULL;
    ui_Button6 = NULL;
    ui_Label30 = NULL;
    ui_Label31 = NULL;
    ui_Label32 = NULL;
    ui_Label33 = NULL;
    ui_Label34 = NULL;
    ui_Spinbox4 = NULL;
    ui_Label35 = NULL;
    ui_Switch2 = NULL;
    ui_Label36 = NULL;
    ui_Label37 = NULL;
    ui_Button9 = NULL;
    ui_Button10 = NULL;
    ui_Label38 = NULL;
    ui_Label39 = NULL;
    ui_Spinbox5 = NULL;
    ui_Label40 = NULL;
}
