// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenMain = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_LabelTemp0 = NULL;
lv_obj_t * ui_LabelWind = NULL;
lv_obj_t * ui_LabelWindDir = NULL;
lv_obj_t * ui_LabelLU0 = NULL;
lv_obj_t * ui_LabelTime = NULL;
lv_obj_t * ui_ButtonSettings = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_LabelTemp1 = NULL;
lv_obj_t * ui_LabelHum0 = NULL;
lv_obj_t * ui_LabelHum2 = NULL;
lv_obj_t * ui_LabelHum1 = NULL;
lv_obj_t * ui_LabelPres0 = NULL;
lv_obj_t * ui_LabelHum3 = NULL;
lv_obj_t * ui_LabelTemp2 = NULL;
lv_obj_t * ui_LabelTemp3 = NULL;
lv_obj_t * ui_LabelPres3 = NULL;
lv_obj_t * ui_LabelPres2 = NULL;
lv_obj_t * ui_LabelPres1 = NULL;
lv_obj_t * ui_LabelLU1 = NULL;
lv_obj_t * ui_LabelLU2 = NULL;
lv_obj_t * ui_LabelLU3 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_LabelWind1 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label21 = NULL;
// event funtions
void ui_event_LabelTemp0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenChart, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenChart_screen_init);
        ClickTemp1(e);
    }
}

void ui_event_LabelWind(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenChart, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenChart_screen_init);
        ClickWindSpeed(e);
    }
}

void ui_event_ButtonSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettings_screen_init);
    }
}

void ui_event_LabelTemp1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        ClickTemp2(e);
        _ui_screen_change(&ui_ScreenChart, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenChart_screen_init);
    }
}

void ui_event_LabelHum0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenChart, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenChart_screen_init);
        ClickHum1(e);
    }
}

void ui_event_LabelHum2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenChart, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenChart_screen_init);
        ClickHum3(e);
    }
}

void ui_event_LabelHum1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenChart, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenChart_screen_init);
        ClickHum2(e);
    }
}

void ui_event_LabelPres0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenChart, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenChart_screen_init);
        ClickPres1(e);
    }
}

void ui_event_LabelHum3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenChart, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenChart_screen_init);
        ClickHum4(e);
    }
}

void ui_event_LabelTemp2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenChart, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenChart_screen_init);
        ClickTemp3(e);
    }
}

void ui_event_LabelTemp3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenChart, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenChart_screen_init);
        ClickTemp4(e);
    }
}

void ui_event_LabelPres3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenChart, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenChart_screen_init);
        ClickPres4(e);
    }
}

void ui_event_LabelPres2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenChart, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenChart_screen_init);
        ClickPres3(e);
    }
}

void ui_event_LabelPres1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenChart, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenChart_screen_init);
        ClickPres2(e);
    }
}

void ui_event_LabelWind1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenChart, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenChart_screen_init);
        ClickWindSpeed(e);
    }
}

// build funtions

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_image_create(ui_ScreenMain);
    lv_image_set_src(ui_Image2, &ui_img_windrose_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -55);
    lv_obj_set_y(ui_Image2, 0);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTemp0 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelTemp0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp0, -52);
    lv_obj_set_y(ui_LabelTemp0, 9);
    lv_obj_set_align(ui_LabelTemp0, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelTemp0, "__.__°C");
    lv_obj_add_flag(ui_LabelTemp0, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelTemp0, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp0, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelTemp0, lv_color_hex(0x2B4767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelTemp0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelTemp0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelTemp0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelTemp0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelTemp0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelTemp0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelTemp0, lv_color_hex(0x5CAFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LabelTemp0, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelWind = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelWind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWind, -177);
    lv_obj_set_y(ui_LabelWind, -14);
    lv_obj_set_align(ui_LabelWind, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWind, "__._kph");
    lv_obj_add_flag(ui_LabelWind, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelWind, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWind, &ui_font_Font24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelWind, lv_color_hex(0x2B4767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelWind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelWind, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelWind, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelWind, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelWind, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelWind, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelWind, lv_color_hex(0x5CAFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LabelWind, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelWindDir = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelWindDir, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWindDir, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWindDir, -365);
    lv_obj_set_y(ui_LabelWindDir, 84);
    lv_obj_set_align(ui_LabelWindDir, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelWindDir, "NNE");
    lv_obj_set_style_text_color(ui_LabelWindDir, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWindDir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWindDir, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLU0 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelLU0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLU0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLU0, -3);
    lv_obj_set_y(ui_LabelLU0, 52);
    lv_obj_set_align(ui_LabelLU0, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelLU0, "N/A");
    lv_obj_set_style_text_color(ui_LabelLU0, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLU0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLU0, &ui_font_Font10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, -263);
    lv_obj_set_y(ui_LabelTime, 5);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelTime, "12:00:00 PM");
    lv_obj_set_style_text_font(ui_LabelTime, &ui_font_Font32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSettings = lv_button_create(ui_ScreenMain);
    lv_obj_set_width(ui_ButtonSettings, 80);
    lv_obj_set_height(ui_ButtonSettings, 37);
    lv_obj_set_x(ui_ButtonSettings, -190);
    lv_obj_set_y(ui_ButtonSettings, -73);
    lv_obj_set_align(ui_ButtonSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -190);
    lv_obj_set_y(ui_Label1, -73);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "SETTINGS");

    ui_LabelTemp1 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp1, -52);
    lv_obj_set_y(ui_LabelTemp1, 76);
    lv_obj_set_align(ui_LabelTemp1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelTemp1, "__.__°C");
    lv_obj_add_flag(ui_LabelTemp1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelTemp1, lv_color_hex(0xFF8888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelTemp1, lv_color_hex(0x2B4767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelTemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelTemp1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelTemp1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelTemp1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelTemp1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelTemp1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelTemp1, lv_color_hex(0x5CAFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LabelTemp1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelHum0 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelHum0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHum0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHum0, 216);
    lv_obj_set_y(ui_LabelHum0, -110);
    lv_obj_set_align(ui_LabelHum0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHum0, "__%");
    lv_obj_add_flag(ui_LabelHum0, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelHum0, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHum0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHum0, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelHum0, lv_color_hex(0x2B4767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelHum0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelHum0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelHum0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelHum0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelHum0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelHum0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelHum0, lv_color_hex(0x5CAFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LabelHum0, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelHum2 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelHum2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHum2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHum2, 216);
    lv_obj_set_y(ui_LabelHum2, 28);
    lv_obj_set_align(ui_LabelHum2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHum2, "__%");
    lv_obj_add_flag(ui_LabelHum2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelHum2, lv_color_hex(0x6EFF72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHum2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHum2, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelHum2, lv_color_hex(0x2B4767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelHum2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelHum2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelHum2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelHum2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelHum2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelHum2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelHum2, lv_color_hex(0x5CAFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LabelHum2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelHum1 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelHum1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHum1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHum1, 216);
    lv_obj_set_y(ui_LabelHum1, -44);
    lv_obj_set_align(ui_LabelHum1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHum1, "__%");
    lv_obj_add_flag(ui_LabelHum1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelHum1, lv_color_hex(0xFF8888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHum1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHum1, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelHum1, lv_color_hex(0x2B4767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelHum1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelHum1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelHum1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelHum1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelHum1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelHum1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelHum1, lv_color_hex(0x5CAFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LabelHum1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelPres0 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelPres0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPres0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPres0, -180);
    lv_obj_set_y(ui_LabelPres0, 88);
    lv_obj_set_align(ui_LabelPres0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPres0, "____._mbar");
    lv_obj_add_flag(ui_LabelPres0, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelPres0, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPres0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPres0, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelPres0, lv_color_hex(0x2B4767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelPres0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelPres0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelPres0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelPres0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelPres0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelPres0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelPres0, lv_color_hex(0x5CAFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LabelPres0, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelHum3 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelHum3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHum3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHum3, 216);
    lv_obj_set_y(ui_LabelHum3, 95);
    lv_obj_set_align(ui_LabelHum3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHum3, "__%");
    lv_obj_add_flag(ui_LabelHum3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelHum3, lv_color_hex(0xFFC874), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHum3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHum3, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelHum3, lv_color_hex(0x2B4767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelHum3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelHum3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelHum3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelHum3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelHum3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelHum3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelHum3, lv_color_hex(0x5CAFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LabelHum3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelTemp2 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelTemp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp2, -52);
    lv_obj_set_y(ui_LabelTemp2, 148);
    lv_obj_set_align(ui_LabelTemp2, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelTemp2, "__.__°C");
    lv_obj_add_flag(ui_LabelTemp2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelTemp2, lv_color_hex(0x6EFF72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelTemp2, lv_color_hex(0x2B4767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelTemp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelTemp2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelTemp2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelTemp2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelTemp2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelTemp2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelTemp2, lv_color_hex(0x5CAFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LabelTemp2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelTemp3 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelTemp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp3, -52);
    lv_obj_set_y(ui_LabelTemp3, 215);
    lv_obj_set_align(ui_LabelTemp3, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelTemp3, "__.__°C");
    lv_obj_add_flag(ui_LabelTemp3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelTemp3, lv_color_hex(0xFFC874), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTemp3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelTemp3, lv_color_hex(0x2B4767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelTemp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelTemp3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelTemp3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelTemp3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelTemp3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelTemp3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelTemp3, lv_color_hex(0x5CAFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LabelTemp3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelPres3 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelPres3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPres3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPres3, -67);
    lv_obj_set_y(ui_LabelPres3, 120);
    lv_obj_set_align(ui_LabelPres3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPres3, "____._mbar");
    lv_obj_add_flag(ui_LabelPres3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelPres3, lv_color_hex(0xFFC874), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPres3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPres3, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelPres3, lv_color_hex(0x2B4767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelPres3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelPres3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelPres3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelPres3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelPres3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelPres3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelPres3, lv_color_hex(0x5CAFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LabelPres3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelPres2 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelPres2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPres2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPres2, -180);
    lv_obj_set_y(ui_LabelPres2, 120);
    lv_obj_set_align(ui_LabelPres2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPres2, "____._mbar");
    lv_obj_add_flag(ui_LabelPres2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelPres2, lv_color_hex(0x6EFF72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPres2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPres2, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelPres2, lv_color_hex(0x2B4767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelPres2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelPres2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelPres2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelPres2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelPres2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelPres2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelPres2, lv_color_hex(0x5CAFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LabelPres2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelPres1 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelPres1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPres1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPres1, -67);
    lv_obj_set_y(ui_LabelPres1, 89);
    lv_obj_set_align(ui_LabelPres1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPres1, "____._mbar");
    lv_obj_add_flag(ui_LabelPres1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelPres1, lv_color_hex(0xFF8888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPres1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPres1, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelPres1, lv_color_hex(0x2B4767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelPres1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelPres1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelPres1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelPres1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelPres1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelPres1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelPres1, lv_color_hex(0x5CAFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LabelPres1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelLU1 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelLU1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLU1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLU1, -3);
    lv_obj_set_y(ui_LabelLU1, 118);
    lv_obj_set_align(ui_LabelLU1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelLU1, "N/A");
    lv_obj_set_style_text_color(ui_LabelLU1, lv_color_hex(0xFF8888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLU1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLU1, &ui_font_Font10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLU2 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelLU2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLU2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLU2, -3);
    lv_obj_set_y(ui_LabelLU2, 191);
    lv_obj_set_align(ui_LabelLU2, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelLU2, "N/A");
    lv_obj_set_style_text_color(ui_LabelLU2, lv_color_hex(0x6EFF72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLU2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLU2, &ui_font_Font10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLU3 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelLU3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLU3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLU3, -3);
    lv_obj_set_y(ui_LabelLU3, 255);
    lv_obj_set_align(ui_LabelLU3, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelLU3, "N/A");
    lv_obj_set_style_text_color(ui_LabelLU3, lv_color_hex(0xFFC874), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLU3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLU3, &ui_font_Font10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -233);
    lv_obj_set_y(ui_Label13, 75);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "1");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -120);
    lv_obj_set_y(ui_Label14, 76);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "2");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -233);
    lv_obj_set_y(ui_Label15, 107);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "3");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -120);
    lv_obj_set_y(ui_Label16, 107);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "4");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 195);
    lv_obj_set_y(ui_Label18, 59);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "3");
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 194);
    lv_obj_set_y(ui_Label7, 124);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "4");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 194);
    lv_obj_set_y(ui_Label19, -13);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "2");
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 195);
    lv_obj_set_y(ui_Label6, -79);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "1");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWind1 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelWind1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWind1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWind1, -177);
    lv_obj_set_y(ui_LabelWind1, 44);
    lv_obj_set_align(ui_LabelWind1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWind1, "__._kph");
    lv_obj_add_flag(ui_LabelWind1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelWind1, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWind1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWind1, &ui_font_Font24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelWind1, lv_color_hex(0x2B4767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelWind1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelWind1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelWind1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelWind1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelWind1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelWind1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelWind1, lv_color_hex(0x5CAFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LabelWind1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label17 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -227);
    lv_obj_set_y(ui_Label17, -40);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Avg:");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -225);
    lv_obj_set_y(ui_Label21, 18);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Gust:");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LabelTemp0, ui_event_LabelTemp0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelWind, ui_event_LabelWind, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSettings, ui_event_ButtonSettings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelTemp1, ui_event_LabelTemp1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelHum0, ui_event_LabelHum0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelHum2, ui_event_LabelHum2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelHum1, ui_event_LabelHum1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelPres0, ui_event_LabelPres0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelHum3, ui_event_LabelHum3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelTemp2, ui_event_LabelTemp2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelTemp3, ui_event_LabelTemp3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelPres3, ui_event_LabelPres3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelPres2, ui_event_LabelPres2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelPres1, ui_event_LabelPres1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelWind1, ui_event_LabelWind1, LV_EVENT_ALL, NULL);

}

void ui_ScreenMain_screen_destroy(void)
{
    if(ui_ScreenMain) lv_obj_del(ui_ScreenMain);

    // NULL screen variables
    ui_ScreenMain = NULL;
    ui_Image2 = NULL;
    ui_LabelTemp0 = NULL;
    ui_LabelWind = NULL;
    ui_LabelWindDir = NULL;
    ui_LabelLU0 = NULL;
    ui_LabelTime = NULL;
    ui_ButtonSettings = NULL;
    ui_Label1 = NULL;
    ui_LabelTemp1 = NULL;
    ui_LabelHum0 = NULL;
    ui_LabelHum2 = NULL;
    ui_LabelHum1 = NULL;
    ui_LabelPres0 = NULL;
    ui_LabelHum3 = NULL;
    ui_LabelTemp2 = NULL;
    ui_LabelTemp3 = NULL;
    ui_LabelPres3 = NULL;
    ui_LabelPres2 = NULL;
    ui_LabelPres1 = NULL;
    ui_LabelLU1 = NULL;
    ui_LabelLU2 = NULL;
    ui_LabelLU3 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Label15 = NULL;
    ui_Label16 = NULL;
    ui_Label18 = NULL;
    ui_Label7 = NULL;
    ui_Label19 = NULL;
    ui_Label6 = NULL;
    ui_LabelWind1 = NULL;
    ui_Label17 = NULL;
    ui_Label21 = NULL;

}
