// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCREENCHART_H
#define UI_SCREENCHART_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenChart
extern void ui_ScreenChart_screen_init(void);
extern void ui_ScreenChart_screen_destroy(void);
extern lv_obj_t * ui_ScreenChart;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart1_Xaxis;
extern lv_obj_t * ui_Chart1_Yaxis1;
extern lv_obj_t * ui_Chart1_Yaxis2;
extern lv_obj_t * ui_LabelChart;
extern void ui_event_ButtonReturn2(lv_event_t * e);
extern lv_obj_t * ui_ButtonReturn2;
extern lv_obj_t * ui_Label20;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

