// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCREENSETTINGS_H
#define UI_SCREENSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSettings
extern void ui_ScreenSettings_screen_init(void);
extern void ui_ScreenSettings_screen_destroy(void);
extern lv_obj_t * ui_ScreenSettings;
extern void ui_event_ButtonReturn(lv_event_t * e);
extern lv_obj_t * ui_ButtonReturn;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_LabelIP2;
extern lv_obj_t * ui_Label9;
extern void ui_event_ButtonWifi(lv_event_t * e);
extern lv_obj_t * ui_ButtonWifi;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Spinbox1;
extern lv_obj_t * ui_Spinbox2;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_LabelConnectedTo;
extern lv_obj_t * ui_Spinbox3;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label27;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Spinbox4;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Spinbox5;
extern lv_obj_t * ui_Label40;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

