// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCREENWIFI_H
#define UI_SCREENWIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenWifi
extern void ui_ScreenWifi_screen_init(void);
extern void ui_ScreenWifi_screen_destroy(void);
extern lv_obj_t * ui_ScreenWifi;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_DropdownSSID;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern void ui_event_TextAreaPassword(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPassword;
extern void ui_event_ButtonSave(lv_event_t * e);
extern lv_obj_t * ui_ButtonSave;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_LabelConsole;
extern void ui_event_ButtonReturn3(lv_event_t * e);
extern lv_obj_t * ui_ButtonReturn3;
extern lv_obj_t * ui_Label23;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

