// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenWifi = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_DropdownSSID = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_TextAreaPassword = NULL;
lv_obj_t * ui_ButtonSave = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_LabelConsole = NULL;
lv_obj_t * ui_ButtonReturn3 = NULL;
lv_obj_t * ui_Label23 = NULL;
// event funtions
void ui_event_TextAreaPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextAreaPassword);
    }
}

void ui_event_ButtonSave(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SaveWifiFromUI(e);
    }
}

void ui_event_ButtonReturn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenMain_screen_init);
    }
}

// build funtions

void ui_ScreenWifi_screen_init(void)
{
    ui_ScreenWifi = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_ScreenWifi);
    lv_obj_set_width(ui_Keyboard1, 464);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 69);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_DropdownSSID = lv_dropdown_create(ui_ScreenWifi);
    lv_dropdown_set_options(ui_DropdownSSID, "Scanning...");
    lv_obj_set_width(ui_DropdownSSID, 369);
    lv_obj_set_height(ui_DropdownSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownSSID, 49);
    lv_obj_set_y(ui_DropdownSSID, -112);
    lv_obj_set_align(ui_DropdownSSID, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownSSID, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label3 = lv_label_create(ui_ScreenWifi);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -186);
    lv_obj_set_y(ui_Label3, -118);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Select SSID:");

    ui_Label4 = lv_label_create(ui_ScreenWifi);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -169);
    lv_obj_set_y(ui_Label4, -61);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Enter Password:");

    ui_TextAreaPassword = lv_textarea_create(ui_ScreenWifi);
    lv_obj_set_width(ui_TextAreaPassword, 129);
    lv_obj_set_height(ui_TextAreaPassword, 41);
    lv_obj_set_x(ui_TextAreaPassword, 144);
    lv_obj_set_y(ui_TextAreaPassword, 52);
    lv_obj_set_style_text_align(ui_TextAreaPassword, LV_ALIGN_CENTER, 0);
    lv_textarea_set_placeholder_text(ui_TextAreaPassword, "Tap here");

    ui_ButtonSave = lv_button_create(ui_ScreenWifi);
    lv_obj_set_width(ui_ButtonSave, 95);
    lv_obj_set_height(ui_ButtonSave, 41);
    lv_obj_set_x(ui_ButtonSave, 91);
    lv_obj_set_y(ui_ButtonSave, -64);
    lv_obj_set_align(ui_ButtonSave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_ScreenWifi);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 90);
    lv_obj_set_y(ui_Label5, -63);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "CONNECT");

    ui_Panel1 = lv_obj_create(ui_ScreenWifi);
    lv_obj_set_width(ui_Panel1, 450);
    lv_obj_set_height(ui_Panel1, 47);
    lv_obj_set_x(ui_Panel1, -3);
    lv_obj_set_y(ui_Panel1, -14);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xE5E3C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelConsole = lv_label_create(ui_ScreenWifi);
    lv_obj_set_width(ui_LabelConsole, 433);
    lv_obj_set_height(ui_LabelConsole, 32);
    lv_obj_set_x(ui_LabelConsole, 18);
    lv_obj_set_y(ui_LabelConsole, 107);
    lv_label_set_text(ui_LabelConsole, "");
    lv_obj_set_scrollbar_mode(ui_LabelConsole, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_LabelConsole, LV_DIR_VER);
    lv_obj_set_style_text_color(ui_LabelConsole, lv_color_hex(0x1A1918), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelConsole, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelConsole, &ui_font_Font10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonReturn3 = lv_button_create(ui_ScreenWifi);
    lv_obj_set_width(ui_ButtonReturn3, 60);
    lv_obj_set_height(ui_ButtonReturn3, 41);
    lv_obj_set_x(ui_ButtonReturn3, 185);
    lv_obj_set_y(ui_ButtonReturn3, -64);
    lv_obj_set_align(ui_ButtonReturn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonReturn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReturn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_ScreenWifi);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 185);
    lv_obj_set_y(ui_Label23, -62);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "SAVE \n& EXIT");
    lv_obj_set_style_text_align(ui_Label23, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextAreaPassword, ui_event_TextAreaPassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSave, ui_event_ButtonSave, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonReturn3, ui_event_ButtonReturn3, LV_EVENT_ALL, NULL);

}

void ui_ScreenWifi_screen_destroy(void)
{
    if(ui_ScreenWifi) lv_obj_del(ui_ScreenWifi);

    // NULL screen variables
    ui_ScreenWifi = NULL;
    ui_Keyboard1 = NULL;
    ui_DropdownSSID = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_TextAreaPassword = NULL;
    ui_ButtonSave = NULL;
    ui_Label5 = NULL;
    ui_Panel1 = NULL;
    ui_LabelConsole = NULL;
    ui_ButtonReturn3 = NULL;
    ui_Label23 = NULL;

}
