// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern void ui_event_ButtonReturn(lv_event_t * e);
extern lv_obj_t * ui_ButtonReturn;
extern lv_obj_t * ui_Label2;
extern void ui_event_SliderAvg(lv_event_t * e);
extern lv_obj_t * ui_SliderAvg;
extern lv_obj_t * ui_LabelAvgSlider;
extern void ui_event_SliderGust(lv_event_t * e);
extern lv_obj_t * ui_SliderGust;
extern lv_obj_t * ui_LabelGustSlider;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

