// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_ScreenWifi.h"
#include "screens/ui_ScreenMain.h"
#include "screens/ui_ScreenSettings.h"
#include "screens/ui_ScreenChart.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_windrose_png);    // assets/windrose.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font10);
LV_FONT_DECLARE(ui_font_Font12);
LV_FONT_DECLARE(ui_font_Font16);
LV_FONT_DECLARE(ui_font_Font20);
LV_FONT_DECLARE(ui_font_Font24);
LV_FONT_DECLARE(ui_font_Font32);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
