// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif
void saveSettings(void);
void SaveWifiFromUI(lv_event_t * e);
void ClickTemp1(lv_event_t * e);
void ClickWindSpeed(lv_event_t * e);
void ClickTemp2(lv_event_t * e);
void ClickHum1(lv_event_t * e);
void ClickHum3(lv_event_t * e);
void ClickHum2(lv_event_t * e);
void ClickPres1(lv_event_t * e);
void ClickHum4(lv_event_t * e);
void ClickTemp3(lv_event_t * e);
void ClickTemp4(lv_event_t * e);
void ClickPres4(lv_event_t * e);
void ClickPres3(lv_event_t * e);
void ClickPres2(lv_event_t * e);
void sendSliderValuesToWindTransmitter(void);
void updateBacklightLive(bool autoMode, int offset);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
