// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

void my_chart_event_cb(lv_event_t * e)
{
	// Your code here
}

void my_chart_event_cb2(lv_event_t * e)
{
	// Your code here
}
