// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_LabelTemp = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_LabelLU1 = NULL;
lv_obj_t * ui_LabelLU2 = NULL;
lv_obj_t * ui_LabelTime = NULL;
lv_obj_t * ui_LabelIP = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Chart1 = NULL;
lv_obj_t * ui_Chart1_Xaxis = NULL;
lv_obj_t * ui_Chart1_Yaxis1 = NULL;
lv_obj_t * ui_Chart1_Yaxis2 = NULL;
lv_obj_t * ui_ButtonSettings = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions
void ui_event_ButtonSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image2, &ui_img_windrose_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -71);
    lv_obj_set_y(ui_Image2, 60);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, -135);
    lv_obj_set_y(ui_LabelTemp, -44);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "999.9°C");
    lv_obj_set_style_text_color(ui_LabelTemp, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -189);
    lv_obj_set_y(ui_Label4, 64);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "69.4kph");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -196);
    lv_obj_set_y(ui_Label5, 101);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "NE");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -56);
    lv_obj_set_y(ui_Label6, -126);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "LAST TEMP\nUPDATE");
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -194);
    lv_obj_set_y(ui_Label7, 15);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "LAST WIND\nUPDATE");
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLU1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelLU1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLU1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLU1, -59);
    lv_obj_set_y(ui_LabelLU1, -108);
    lv_obj_set_align(ui_LabelLU1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLU1, "0s");
    lv_obj_set_style_text_color(ui_LabelLU1, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLU1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLU2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelLU2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLU2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLU2, -192);
    lv_obj_set_y(ui_LabelLU2, 38);
    lv_obj_set_align(ui_LabelLU2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLU2, "0s");
    lv_obj_set_style_text_color(ui_LabelLU2, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLU2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, -169);
    lv_obj_set_y(ui_LabelTime, -119);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "12:00:00 PM");
    lv_obj_set_style_text_font(ui_LabelTime, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIP = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIP, -196);
    lv_obj_set_y(ui_LabelIP, -94);
    lv_obj_set_align(ui_LabelIP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIP, "255.255.255.255");
    lv_obj_set_style_text_font(ui_LabelIP, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -203);
    lv_obj_set_y(ui_Label3, -80);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "RSSI: -100dB");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart1 = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_Chart1, 209);
    lv_obj_set_height(ui_Chart1, 237);
    lv_obj_set_x(ui_Chart1, 126);
    lv_obj_set_y(ui_Chart1, -9);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Chart1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart1, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);

    ui_Chart1_Xaxis = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart1_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart1_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart1_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart1,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Xaxis, 0, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart1_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart1_Xaxis, 0, 0 > 0 ? 0 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart1_Xaxis, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Xaxis, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_Chart1_Xaxis, false);
    ui_Chart1_Yaxis1 = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart1_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart1_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart1_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart1,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart1_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart1_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Yaxis1, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_Chart1_Yaxis1, false);
    ui_Chart1_Yaxis2 = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart1_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart1_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart1_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart1,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart1_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart1_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_Chart1_Yaxis2, false);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_series_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

    lv_obj_set_style_line_width(ui_Chart1, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_Chart1, 3, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart1, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_ButtonSettings = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonSettings, 80);
    lv_obj_set_height(ui_ButtonSettings, 37);
    lv_obj_set_x(ui_ButtonSettings, -112);
    lv_obj_set_y(ui_ButtonSettings, -87);
    lv_obj_set_align(ui_ButtonSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -112);
    lv_obj_set_y(ui_Label1, -87);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "SETTINGS");

    lv_obj_add_event_cb(ui_ButtonSettings, ui_event_ButtonSettings, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image2 = NULL;
    ui_LabelTemp = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_LabelLU1 = NULL;
    ui_LabelLU2 = NULL;
    ui_LabelTime = NULL;
    ui_LabelIP = NULL;
    ui_Label3 = NULL;
    ui_Chart1 = NULL;
    ui_ButtonSettings = NULL;
    ui_Label1 = NULL;

}
