// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_ButtonReturn = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_SliderAvg = NULL;
lv_obj_t * ui_LabelAvgSlider = NULL;
lv_obj_t * ui_SliderGust = NULL;
lv_obj_t * ui_LabelGustSlider = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
// event funtions
void ui_event_ButtonReturn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}
/*
void ui_event_SliderAvg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_text_value(ui_LabelAvgSlider, target, "", "s");
    }
}

void ui_event_SliderGust(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_text_value(ui_LabelGustSlider, target, "", "s");
    }
}*/

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonReturn = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonReturn, 100);
    lv_obj_set_height(ui_ButtonReturn, 40);
    lv_obj_set_x(ui_ButtonReturn, -176);
    lv_obj_set_y(ui_ButtonReturn, -103);
    lv_obj_set_align(ui_ButtonReturn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonReturn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonReturn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -179);
    lv_obj_set_y(ui_Label2, -103);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "RETURN");

    ui_SliderAvg = lv_slider_create(ui_Screen2);
    lv_slider_set_range(ui_SliderAvg, 0, 60);
    lv_slider_set_value(ui_SliderAvg, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderAvg) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_SliderAvg, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderAvg, 252);
    lv_obj_set_height(ui_SliderAvg, 10);
    lv_obj_set_x(ui_SliderAvg, -93);
    lv_obj_set_y(ui_SliderAvg, -49);
    lv_obj_set_align(ui_SliderAvg, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SliderAvg, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SliderAvg,
                                                                                                lv_obj_get_style_pad_right(ui_SliderAvg, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_LabelAvgSlider = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelAvgSlider, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAvgSlider, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAvgSlider, 58);
    lv_obj_set_y(ui_LabelAvgSlider, -50);
    lv_obj_set_align(ui_LabelAvgSlider, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAvgSlider, "10");

    ui_SliderGust = lv_slider_create(ui_Screen2);
    lv_slider_set_range(ui_SliderGust, 0, 60);
    lv_slider_set_value(ui_SliderGust, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderGust) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_SliderGust, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderGust, 246);
    lv_obj_set_height(ui_SliderGust, 10);
    lv_obj_set_x(ui_SliderGust, -96);
    lv_obj_set_y(ui_SliderGust, -1);
    lv_obj_set_align(ui_SliderGust, LV_ALIGN_CENTER);
    

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SliderGust, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SliderGust,
                                                                                                 lv_obj_get_style_pad_right(ui_SliderGust, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_LabelGustSlider = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelGustSlider, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGustSlider, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGustSlider, 53);
    lv_obj_set_y(ui_LabelGustSlider, 0);
    lv_obj_set_align(ui_LabelGustSlider, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGustSlider, "3");

    ui_Label10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -144);
    lv_obj_set_y(ui_Label10, -67);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Average Window");

    ui_Label11 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -153);
    lv_obj_set_y(ui_Label11, -23);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Gust Window");

    lv_obj_add_event_cb(ui_ButtonReturn, ui_event_ButtonReturn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderAvg, ui_event_SliderAvg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderGust, ui_event_SliderGust, LV_EVENT_ALL, NULL);

}



void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_ButtonReturn = NULL;
    ui_Label2 = NULL;
    ui_SliderAvg = NULL;
    ui_LabelAvgSlider = NULL;
    ui_SliderGust = NULL;
    ui_LabelGustSlider = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;

}
