// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_LabelTemp = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_LabelLU1 = NULL;
lv_obj_t * ui_LabelLU2 = NULL;
lv_obj_t * ui_LabelTime = NULL;
lv_obj_t * ui_LabelIP = NULL;
lv_obj_t * ui_Label3 = NULL;

// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image2, &ui_img_windrose_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -71);
    lv_obj_set_y(ui_Image2, 60);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    

    ui_LabelTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, -135);
    lv_obj_set_y(ui_LabelTemp, -44);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "999.9°C");
    lv_obj_set_style_text_color(ui_LabelTemp, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -189);
    lv_obj_set_y(ui_Label4, 64);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "69.4kph");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -196);
    lv_obj_set_y(ui_Label5, 101);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "NE");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -56);
    lv_obj_set_y(ui_Label6, -126);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "LAST TEMP\nUPDATE");
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -194);
    lv_obj_set_y(ui_Label7, 15);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "LAST WIND\nUPDATE");
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLU1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelLU1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLU1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLU1, -59);
    lv_obj_set_y(ui_LabelLU1, -108);
    lv_obj_set_align(ui_LabelLU1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLU1, "0s");
    lv_obj_set_style_text_color(ui_LabelLU1, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLU1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLU2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelLU2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLU2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLU2, -192);
    lv_obj_set_y(ui_LabelLU2, 38);
    lv_obj_set_align(ui_LabelLU2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLU2, "0s");
    lv_obj_set_style_text_color(ui_LabelLU2, lv_color_hex(0x00DFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLU2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, -169);
    lv_obj_set_y(ui_LabelTime, -119);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "12:00:00 PM");
    lv_obj_set_style_text_font(ui_LabelTime, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIP = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIP, -196);
    lv_obj_set_y(ui_LabelIP, -94);
    lv_obj_set_align(ui_LabelIP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIP, "255.255.255.255");
    lv_obj_set_style_text_font(ui_LabelIP, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -203);
    lv_obj_set_y(ui_Label3, -80);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "RSSI: -100dB");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image2 = NULL;
    ui_LabelTemp = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_LabelLU1 = NULL;
    ui_LabelLU2 = NULL;
    ui_LabelTime = NULL;
    ui_LabelIP = NULL;
    ui_Label3 = NULL;

}
